language: c++

compiler:
  - gcc
  - clang
  
os:
  - linux
  - osx
  
addons:
  apt:
    packages:
      - libglew-dev
      - libfreetype6-dev
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glfw3   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew    ; fi
  - if [[ ! "$TRAVIS_OS_NAME" == "osx" ]]; then sudo add-apt-repository -y ppa:smspillaz/cmake-2.8.12 && sudo apt-get update -y && sudo apt-get install -y cmake-data && sudo apt-get install -y cmake ; fi
before_script:
  #Install GLFW
  - git clone https://github.com/glfw/glfw.git
  - mkdir glfw/build
  - cd glfw/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=~/ -DBUILD_SHARED_LIBS=1
  - make
  - sudo make install
  - cd -
  #Install glm
  - git clone https://github.com/g-truc/glm.git
  - mkdir glm/build
  - cd glm/build
  - cmake ..
  - make
  - sudo make install
  - cd -
  #Install Commons
  - git clone https://github.com/ICStoolbox/Commons.git
  - mkdir Commons/build
  - cd Commons/build
  - cmake ..
  - make 
  - sudo make install
  - cd -
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - cd -
